#!/usr/bin/env ruby

require 'rbbt-util'
require 'rbbt/util/simpleopt'

$0 = "rbbt #{$previous_commands*" "} #{ File.basename(__FILE__) }" if $previous_commands

options = SOPT.setup <<EOF

Bootstrap Appris resources

$ #{$0} [options] <filename.tsv|->

Use - to read from STDIN

-h--help Print this help

EOF
if options[:help]
  if defined? rbbt_usage
    rbbt_usage 
  else
    puts SOPT.doc
  end
  exit 0
end

require 'rbbt/workflow'
Workflow.require_workflow "Appris"

%w(Hsa Mmu Rno).each do |organism|
  codes = Organism.organism_codes(organism)
  scientific_name = Organism.scientific_name(organism).downcase.sub(" ", "_")
  builds = {}
  codes.each do |code|
    build = Organism.GRC_build(code)
    builds[build] ||= []
    builds[build] << code
  end
  builds.each do |build, orgs|
    begin
      Log.tsv Appris[organism][build].protein_annotations.tsv
      Log.tsv Appris[organism][build].principal_isoforms.tsv
      Log.tsv Appris[organism][build].principal_isoform_proteins.tsv
    rescue
    end
  end
end
